// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGithubActionLog(arg1) {
  return window['go']['main']['App']['GetGithubActionLog'](arg1);
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function SendGithubAction(arg1, arg2) {
  return window['go']['main']['App']['SendGithubAction'](arg1, arg2);
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
