name: Wails build

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: PoCopilot-linux-amd64
            os: ubuntu-latest
            platform: linux/amd64
          - name: PoCopilot-windows-amd64.exe
            os: windows-latest
            platform: windows/amd64
          - name: PoCopilot
            os: macos-latest
            platform: darwin/universal

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install dependencies
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.8.1
          npm i react
          npm install npm-force-resolutions --save-dev

      - name: Build Wails Application
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
          nsis: false
          webview2: embed
          go-version: 1.21
          node-version: 18.x
