name: Wails build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: PoCopilot-linux-amd64, platform: linux/amd64, os: ubuntu-latest},
          {name: PoCopilot-windows-amd64.exe, platform: windows/amd64, os: windows-latest},
          {name: PoCopilot, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          cd frontend && npm i react && npm install antd --save && npm i

      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          nsis: false
          wails-build-webview2: embed
          go-version: 1.21
          node-version: 18.x