name: Wails build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        platform: [linux/amd64, windows/amd64, darwin/universal]
        include:
          - name: PoCopilot-linux-amd64
            os: ubuntu-latest
            platform: linux/amd64
          - name: PoCopilot-windows-amd64.exe
            os: windows-latest
            platform: windows/amd64
          - name: PoCopilot
            os: macos-latest
            platform: darwin/universal

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          cd frontend && npm install react antd --save && npm install

      - name: Build Wails Application
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
          nsis: false
          webview2: embed
          go-version: 1.21
          node-version: 18.x
